In [75]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_pickle("./northnf")
df['dev'] = df.Flow - df.intervalMean

In [76]:
df.head()

,DMA,Date,Time,Flow,hour,day_of_week,intervalMean,exist,dev
0,71,01/04/2016,03:00:00,0.089,3,0,0.062630,False,0.026370
1,71,01/04/2016,03:15:00,0.033,3,0,0.062000,False,-0.029000
2,71,01/04/2016,03:30:00,0.067,3,0,0.073370,False,-0.006370
3,71,01/04/2016,03:45:00,0.111,3,0,0.071778,False,0.039222
4,71,02/04/2016,03:00:00,0.078,3,3,0.063392,False,0.014608

In [77]:
#values = df.values
#groups = [3, 5, 6, 8]
#i = 1
## plot each column
#plt.figure()
#for group in groups:#
	#plt.subplot(len(groups), 1, i)
	#plt.plot(values[:, group])
	#plt.title(df.columns[group], y=0.5, loc='right')
	#i += 1
#plt.show()

In [78]:
df["t-4dev"] = df.groupby("DMA").dev.shift(-4)
df["t-8dev"] = df.groupby("DMA").dev.shift(-8)
df["t-12dev"] = df.groupby("DMA").dev.shift(-12)
df["t-16dev"] = df.groupby("DMA").dev.shift(-16)

df["t+4Leak"] = df.groupby("DMA").exist.shift(4)
df["t+8Leak"] = df.groupby("DMA").exist.shift(8)
df["t+12Leak"] = df.groupby("DMA").exist.shift(12)
df["t+16Leak"] = df.groupby("DMA").exist.shift(16)

In [79]:
df.head()

,DMA,Date,Time,Flow,hour,day_of_week,intervalMean,exist,dev,t-4dev,t-8dev,t-12dev,t-16dev,t+4Leak,t+8Leak,t+12Leak,t+16Leak
0,71,01/04/2016,03:00:00,0.089,3,0,0.062630,False,0.026370,0.014608,-0.020870,-0.018630,0.014765,NaN,NaN,NaN,NaN
1,71,01/04/2016,03:15:00,0.033,3,0,0.062000,False,-0.029000,0.029451,-0.012333,-0.018000,0.023451,NaN,NaN,NaN,NaN
2,71,01/04/2016,03:30:00,0.067,3,0,0.073370,False,-0.006370,0.097098,-0.053370,0.048630,-0.009314,NaN,NaN,NaN,NaN
3,71,01/04/2016,03:45:00,0.111,3,0,0.071778,False,0.039222,0.036569,-0.003815,-0.004778,0.029627,NaN,NaN,NaN,NaN
4,71,02/04/2016,03:00:00,0.078,3,3,0.063392,False,0.014608,-0.020870,-0.018630,0.014765,0.031275,False,NaN,NaN,NaN

In [80]:
data = df[["Flow", "dev","t-4dev","t-8dev","t-12dev","t-16dev","t+4Leak","t+8Leak","t+12Leak","t+16Leak","exist"]]
data.head(100)

,Flow,dev,t-4dev,t-8dev,t-12dev,t-16dev,t+4Leak,t+8Leak,t+12Leak,t+16Leak,exist
0,0.089,0.026370,0.014608,-0.020870,-0.018630,0.014765,NaN,NaN,NaN,NaN,False
1,0.033,-0.029000,0.029451,-0.012333,-0.018000,0.023451,NaN,NaN,NaN,NaN,False
2,0.067,-0.006370,0.097098,-0.053370,0.048630,-0.009314,NaN,NaN,NaN,NaN,False
3,0.111,0.039222,0.036569,-0.003815,-0.004778,0.029627,NaN,NaN,NaN,NaN,False
4,0.078,0.014608,-0.020870,-0.018630,0.014765,0.031275,False,NaN,NaN,NaN,False
5,0.100,0.029451,-0.012333,-0.018000,0.023451,0.047627,False,NaN,NaN,NaN,False
6,0.167,0.097098,-0.053370,0.048630,-0.009314,-0.015118,False,NaN,NaN,NaN,False
7,0.111,0.036569,-0.003815,-0.004778,0.029627,-0.023275,False,NaN,NaN,NaN,False
8,0.056,-0.020870,-0.018630,0.014765,0.031275,0.015370,False,False,NaN,NaN,False
9,0.067,-0.012333,-0.018000,0.023451,0.047627,0.027000,False,False,NaN,NaN,False
10,0.033,-0.053370,0.048630,-0.009314,-0.015118,0.093630,False,False,NaN,NaN,False
11,0.089,-0.003815,-0.004778,0.029627,-0.023275,0.128222,False,False,NaN,NaN,False
12,0.044,-0.018630,0.014765,0.031275,0.015370,0.003608,False,False,False,NaN,False
13,0.044,-0.018000,0.023451,0.047627,0.027000,0.018451,False,False,False,NaN,False
14,0.122,0.048630,-0.009314,-0.015118,0.093630,-0.013902,False,False,False,NaN,False
15,0.067,-0.004778,0.029627,-0.023275,0.128222,0.025569,False,False,False,NaN,False
16,0.089,0.014765,0.031275,0.015370,0.003608,-0.010922,False,False,False,False,False
17,0.111,0.023451,0.047627,0.027000,0.018451,-0.010098,False,False,False,False,False
18,0.078,-0.009314,-0.015118,0.093630,-0.013902,0.034902,False,False,False,False,False
19,0.111,0.029627,-0.023275,0.128222,0.025569,-0.009941,False,False,False,False,False
20,0.111,0.031275,0.015370,0.003608,-0.010922,-0.005509,False,False,False,False,False
21,0.122,0.047627,0.027000,0.018451,-0.010098,-0.005000,False,False,False,False,False
22,0.067,-0.015118,0.093630,-0.013902,0.034902,-0.024925,False,False,False,False,False
23,0.056,-0.023275,0.128222,0.025569,-0.009941,0.023528,False,False,False,False,False
24,0.078,0.015370,0.003608,-0.010922,-0.005509,-0.032870,False,False,False,False,False
25,0.089,0.027000,0.018451,-0.010098,-0.005000,-0.001333,False,False,False,False,False
26,0.167,0.093630,-0.013902,0.034902,-0.024925,0.002630,False,False,False,False,False
27,0.200,0.128222,0.025569,-0.009941,0.023528,0.018185,False,False,False,False,False
28,0.067,0.003608,-0.010922,-0.005509,-0.032870,-0.010922,False,False,False,False,False
29,0.089,0.018451,-0.010098,-0.005000,-0.001333,-0.032098,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
70,0.222,0.148630,0.008075,0.101686,0.086098,0.035630,False,False,False,False,False
71,0.122,0.050222,0.023528,0.140627,0.047569,0.007185,False,False,False,False,False
72,0.122,0.049491,0.003765,0.036608,0.067130,0.020275,False,False,False,False,False
73,0.089,0.006000,0.056451,0.173451,0.042667,0.081627,False,False,False,False,False
74,0.089,0.008075,0.101686,0.086098,0.035630,0.039882,False,False,False,False,False
75,0.100,0.023528,0.140627,0.047569,0.007185,0.064725,False,False,False,False,False
76,0.078,0.003765,0.036608,0.067130,0.020275,0.066078,False,False,False,False,False
77,0.144,0.056451,0.173451,0.042667,0.081627,0.189902,False,False,False,False,False
78,0.189,0.101686,0.086098,0.035630,0.039882,0.068902,False,False,False,False,False
79,0.222,0.140627,0.047569,0.007185,0.064725,0.045059,False,False,False,False,False
80,0.100,0.036608,0.067130,0.020275,0.066078,0.070370,False,False,False,False,False
81,0.244,0.173451,0.042667,0.081627,0.189902,0.049000,False,False,False,False,False
82,0.156,0.086098,0.035630,0.039882,0.068902,0.026630,False,False,False,False,False
83,0.122,0.047569,0.007185,0.064725,0.045059,0.028222,False,False,False,False,False
84,0.144,0.067130,0.020275,0.066078,0.070370,0.083491,False,False,False,False,False
85,0.122,0.042667,0.081627,0.189902,0.049000,0.006000,False,False,False,False,False
86,0.122,0.035630,0.039882,0.068902,0.026630,0.075075,False,False,False,False,False
87,0.100,0.007185,0.064725,0.045059,0.028222,0.067528,False,False,False,False,False
88,0.100,0.020275,0.066078,0.070370,0.083491,0.092765,False,False,False,False,False
89,0.156,0.081627,0.189902,0.049000,0.006000,0.056451,False,False,False,False,False
90,0.122,0.039882,0.068902,0.026630,0.075075,0.112686,False,False,False,False,False
91,0.144,0.064725,0.045059,0.028222,0.067528,0.096627,False,False,False,False,False
92,0.144,0.066078,0.070370,0.083491,0.092765,0.058608,False,False,False,False,False
93,0.278,0.189902,0.049000,0.006000,0.056451,0.073451,False,False,False,False,False
94,0.156,0.068902,0.026630,0.075075,0.112686,0.041098,False,False,False,False,False
95,0.133,0.045059,0.028222,0.067528,0.096627,0.058569,False,False,False,False,False
96,0.133,0.070370,0.083491,0.092765,0.058608,0.056130,False,False,False,False,False
97,0.111,0.049000,0.006000,0.056451,0.073451,0.064667,False,False,False,False,False
98,0.100,0.026630,0.075075,0.112686,0.041098,0.013630,False,False,False,False,False
99,0.100,0.028222,0.067528,0.096627,0.058569,0.051185,False,False,False,False,False

In [81]:
data.isnull().sum()

Flow           0
dev            0
t-4dev      2096
t-8dev      4192
t-12dev     6288
t-16dev     8384
t+4Leak     2096
t+8Leak     4192
t+12Leak    6288
t+16Leak    8384
exist          0
dtype: int64

In [82]:
data.shape[0]

760047

In [88]:
data = data.dropna(subset=['t-4dev', 't-8dev', 't-12dev', 't-16dev'], how='any') 
data["t+4Leak"].fillna(False, inplace=True)
data["t+8Leak"].fillna(False, inplace=True)
data["t+12Leak"].fillna(False, inplace=True)
data["t+16Leak"].fillna(False, inplace=True)
data.isnull().sum()

Flow        0
dev         0
t-4dev      0
t-8dev      0
t-12dev     0
t-16dev     0
t+4Leak     0
t+8Leak     0
t+12Leak    0
t+16Leak    0
exist       0
dtype: int64

In [89]:
data.shape[0]

751663

In [90]:
data.to_pickle("./trainingSet")

In [91]:
data[data["exist"] == True].shape[0]

6024

In [92]:
data[data["exist"] == False].shape[0]

745639